FROM envoyproxy/envoy-alpine-dev:latest

RUN apk update && \
    apk add python3 bash curl && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    rm -r /root/.cache

RUN pip3 install flask>=3.0.2 requests>=2.18.4 Jinja2>=3.1.2 markupsafe>=2.1.1

RUN mkdir /code
ADD ./service.py /code

EXPOSE 8080

CMD ["python3", "/code/service.py"]
