name: Create RSA Cert

# on: [push]
on: 
  workflow_dispatch:
jobs:
  deploy:
    name: Generate certif 
    runs-on: ubuntu-latest
    env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: generate a new RSA private key
      run: |
        echo "generate a new RSA private key and save it to a file named "castore.key" with a key length of 2048 bits."
        openssl genrsa -out castore.key 2048
        echo "list files: "
        ls
        echo "castore.key content: "
        cat castore.key


    # - name: Set up Terraform Environment
    #   run: |
    #     wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
    #     unzip terraform_0.15.5_linux_amd64.zip
    #     chmod +x terraform
    #     mv terraform /usr/local/bin/
        
    # - name: Configure AWS CLI
    #   uses: aws-actions/configure-aws-credentials@v3.0.2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: eu-west-2 

    # - name: Initialize Terraform
    #   run: |
    #     terraform init -upgrade -backend-config="bucket=ecs-self-signed-remote-state" \
    #                     -backend-config="key=terraform.tfstate" \
    #                     -backend-config="region=eu-west-2"

    # - name: Terraform Validate
    #   run: terraform validate
        
    # - name: Apply Terraform Changes
    #   run: |
    #     terraform apply -auto-approve 
    #     REPO_URI=$(aws ecr describe-repositories --repository-names fargate-repo --query 'repositories[].repositoryUri' --output text)
    #     echo $REPO_URI
     
    # - uses: docker-practice/actions-setup-docker@master
    # - name: Install docker
    #   run: |
    #       set -x
    #       docker version
        
    # - name: Push image to repo
    #   run: |
    #       echo "building image"
    #       docker version
    #       docker build -t hello-world .
        
    #       REPO_URI=$(aws ecr describe-repositories --repository-names fargate-repo --query 'repositories[].repositoryUri' --output text)
    #       echo $REPO_URI
    #       docker tag hello-world $REPO_URI

