name: 91. Delete All ECR Images

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Delete all images from ECR repositories
        run: |
          for repo in proxy app; do
            echo "Deleting images in repository: $repo"
            
            image_ids=$(aws ecr list-images \
              --repository-name "$repo" \
              --query 'imageIds[*]' \
              --output json)

            if [ "$image_ids" = "[]" ]; then
              echo "No images found in $repo"
            else
              echo "$image_ids" > image_ids.json
              aws ecr batch-delete-image \
                --repository-name "$repo" \
                --image-ids file://image_ids.json
              echo "Deleted images from $repo"
            fi
          done
