name: Create RSA Cert

# on: [push]
on: 
  workflow_dispatch:
jobs:
  deploy:
    name: Generate certif 
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2 
        MY_DOMAIN: marat.don.com

    steps:

    - name: remove certificate from ACM
      run: |
        cert_arn=$(aws acm list-certificates --output json --query "CertificateSummaryList[?DomainName=='$MY_DOMAIN'].CertificateArn")
        echo $cert_arn
        aws acm delete-certificate --certificate-arn $cert_arn

