name: Delete RSA Cert

# on: [push]
on: 
  workflow_dispatch:
jobs:
  deploy:
    name: Remove certif 
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ variables.AWS_REGION }}
        MY_DOMAIN: ${{ secrets.domain_name }}

    steps:
      
    - name: remove certificate from ACM
      run: |
        # List all certificates
        certificates=$(aws acm list-certificates --query "CertificateSummaryList[?contains(DomainName, '$MY_DOMAIN')].CertificateArn" --output text)
        echo "certs: $certificates"

        # Remove each certificate
        for cert_arn in $certificates; do
          aws acm delete-certificate --certificate-arn "$cert_arn"
          echo "Certificate $cert_arn deleted."
        done
