name: 90. Destroy Traffic Mirroring QA resources

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_tfe_token: ${{ secrets.TF_CLOUD_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Set up Terraform Environment
        run: |
          wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
          unzip terraform_0.15.5_linux_amd64.zip
          chmod +x terraform
          mv terraform /usr/local/bin/

     
      - name: Terraform Init
        working-directory: ./tests
        run: terraform init

      - name: Terraform Apply
        working-directory: ./tests
        run: terraform destroy -auto-approve -var "source_eni_id= "   -var "task_private_ip=1.2.3.4"

