name: Deploy Infrastructure

# on: [push]
on: 
  workflow_dispatch:
jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_REGION: eu-west-2 

    steps:
    - uses: docker-practice/actions-setup-docker@master
    - name: Install docker
      run: |
          set -x
          docker version

    - uses: actions/checkout@v4
    - name: Checkout Code
      run: |
        ls
        docker build -t simple-docker-image .
        
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2 

        
    - name: Push image to repo   
      run: |
          echo "building image"
          docker version        
          REPO_URI=$(aws ecr describe-repositories --repository-names ttest --query 'repositories[].repositoryUri' --output text)
          echo $REPO_URI
          docker tag simple-docker-image:latest $REPO_URI
          echo "the region is $AWS_REGION"
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI
          docker push $REPO_URI
